package alez:api;

// WIT documentation: https://component-model.bytecodealliance.org/design/wit.html

world api {
  record message {
    content: string,
    name: string,
  }

  import cool-print: func();
  
  export init-plugin: func();

  export greet: func(msg: message);
}
